apply plugin: "maven-publish"

tasks.register('sourceJar', Jar) {
    from android.sourceSets.main.java.srcDirs
    archiveClassifier.set("sources")
}

def groupId = LIBRARY_GROUP
def artifactId = LIBRARY_ARTIFACT_ID
def versionName = LIBRARY_VERSION_NAME
def debugSuffix = "-debug"
def releaseSuffix = ""

def runtimeImplDepNames = []
def impl = configurations.named("implementation")
if (impl != null) {
    runtimeImplDepNames = impl.allDependencies.collect { it.name }.findAll { it != null }.toSet()
}

def gitLabApi = System.getenv("CI_API_V4_URL")
def gitLabProjectId = System.getenv("CI_PROJECT_ID")
def gitLabJobToken = System.getenv("CI_JOB_TOKEN")

afterEvaluate {
    publishing {
        publications {
            LibraryRelease(MavenPublication) {
                from components.getByName("release")
                setGroupId(groupId)
                setArtifactId(artifactId)
                version versionName + releaseSuffix
                // artifact(sourceJar)
            }

            LibraryDebug(MavenPublication) {
                from components.getByName("debug")
                setGroupId(groupId)
                setArtifactId(artifactId)
                version versionName + debugSuffix
                // artifact(sourceJar)
            }
        }

        publications.configureEach {
            pom.withXml {
                def node = asNode()
                def deps = node.dependencies.'*'.findAll { depNode ->
                    depNode.scope.text() == "runtime" &&
                            runtimeImplDepNames.contains(depNode.artifactId.text())
                }
                deps.each { depNode ->
                    depNode.scope*.value = "compile"
                }
            }
        }

        repositories {
            if (gitLabApi && gitLabProjectId && gitLabJobToken) {
                maven {
                    name = "GitLab"
                    url = uri("${gitLabApi}/projects/${gitLabProjectId}/packages/maven")
                    credentials(HttpHeaderCredentials) {
                        name = "Job-Token"
                        value = gitLabJobToken
                    }
                    authentication {
                        header(HttpHeaderAuthentication)
                    }
                }
            }
        }
    }

    tasks.named("publishToMavenLocal") {
        doLast {
            def prettyPrint = { 1.upto(100, { print "=" }); println() }

            println()
            prettyPrint()
            println("PUBLICATION FINISHED")
            println("Artifact RELEASE: " + groupId + ":" + artifactId + ":" + versionName + releaseSuffix)
            println("Artifact DEBUG: " + groupId + ":" + artifactId + ":" + versionName + debugSuffix)
            prettyPrint()
        }
    }
}